[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "limetr"
version = "0.2.0"
description = "Robust linear mixed effects model with trimming for outlier detection"
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = "BSD-2-Clause"
keywords = ["mixed-effects", "robust-regression", "statistics", "trimming", "outlier-detection"]

authors = [
    { name = "IHME Math Sciences", email = "ihme.math.sciences@gmail.com" },
]

classifiers = [
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Mathematics",
]

dependencies = ["numpy>=1.25.1", "scipy>=1.11.1", "matplotlib>=3.7.2", "spmat>=0.1.0"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = ["sphinx", "sphinx-autodoc-typehints", "furo"]

[project.urls]
github = "https://github.com/ihmeuw-msca/limetr"

[tool.sphinx]
project = "limetr"
author = "IHME Math Sciences"
copyright = "2025, IHME Math Sciences"
version = "0.2.0"